### ISSUE TITLE
need to fix path error which will crash down ue when turntable publish in maya

### ISSUE THREAD

**Issue by jackiezxt** [ue4plugins/tk-framework-unrealqt#10]
https://github.com/ue4plugins/tk-framework-unrealqt/blob/fd1f0a48e9fdf22231ec34651972a1bd2da9da85/hooks/tk-multi-publish2/tk-maya/basic/publish_turntable.py#L1029
https://github.com/ue4plugins/tk-framework-unrealqt/blob/fd1f0a48e9fdf22231ec34651972a1bd2da9da85/hooks/tk-multi-publish2/tk-maya/basic/publish_turntable.py#L974

When the username was too long on Windows 10, it will use` "“~”"` instead, but python doesn't recognize that, so does unreal too. Because of the character `“~”`,  UE will crash when publishing the turntable review item in Maya. I fix it in my hook, just turned and expanded the `"~"` to a full path. So, can you fix this in the "publish_turntable.py" file？

**Comment by ryanmayeda** [comment]
Would you be able to share the exact path you ended up with so we can reproduce this on our side?

**Comment by ryanmayeda** [comment]
We had to revisit the integration for UE 5.4 + Python 3.11 + PySide6 and included a fix for this.  Hopefully it's better late than never.
